// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnuemlogcrmizfpkonll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudWVtbG9nY3JtaXpmcGtvbmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDE3NjgsImV4cCI6MjA2MTA3Nzc2OH0.vqka6er3wMzs-_M_ccIUyaXdxx4ZDHpOkYkMJWSUAEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);